# ----
# Site

title: 知人
description: Zhiren API documentation.
url: https://zhiren.com
google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  object:
    title: 对象
    position: 2
  sub_company:
    title: 分公司 API
    position: 3
  department:
    title: 部门 API
    position: 4
  employee:
    title: 员工 API
    position: 5
  attendance:
    title: 出勤 API
    position: 6
  fangke:
    title: 访客系统 API
    position: 11
  # api:
  #   title: APIs
  #   position: 4
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
  - patch
